src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks
 *
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieure à la date d'aujourd'hui.", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être plus éloignée que la date d'arrivée.")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Callback appelé à chaque réservation, il permet d'initialiser les certains données
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }
        if (empty($this->amount)) {
            //prix de lannonce * nombre de nuits
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    /*
    public function isBookableDate()
    {
        $formatDay = function ($day) {
            return $day->format('Y-m-d');
        };
        //1- il faut connaitre les dates qui sont impossible pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();

        //2- il faut comparer les dates choisies avec c' elles impossibles
        $bookingDays = $this->getDays();

        // Tableau qui contient les chaines de caractères de mes journées de réservation

        //transformation en chaine de caractère pour pouvoir les comparées
        $days = array_map(
            $formatDay,
            $bookingDays
        );
        $notAvailable = array_map(
            $formatDay,
            $notAvailableDays
        );

        // on parcours et on compare
        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) return false;
        }
        //3- il faut qu'elle retourne true ou false pour savoir la possibilité de reservation
        return true;
    }
*/
    /**
     * Permet de connaitre les jours qui correspondent à ma réservation
     * @return array Un tableau d'objets DateTime représentant les jours de la réservation
     */
    /*
    public function getDays()
    {
        //timestamp days
        $results = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );
        //timestamp days to dateTime object
        $days = array_map(
            function ($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            },
            $results
        );
        return $days;
    }
    */

    public function isBookableDates() {
        // 1) Il faut connaitre les dates qui sont impossibles pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();
        // 2) Il faut comparer les dates choisies avec les dates impossibles
        $bookingDays = $this->getDays();

        $formatDay = function($day) {
            return $day->format('Y-m-d');
        };

        // Tableau qui contient des chaines de caractères de mes journées
        $days = array_map($formatDay, $bookingDays);

        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach($days as $day) {
            if(array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Permet de récupérer un tableau des journées qui correspondent à ma réservation
     *
     * @return array Un tableau d'objets DateTime représentant les jours de la réservation
     */
    public function getDays() {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getDuration()
    {
        $diff = $this->getEndDate()->diff($this->getStartDate());

        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Une autre utilisateur s'est  dejâ inscrit avec ce mail, merci de se connecter ou de renitialiser votre mot de passe !, "
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min=3, max=15, minMessage="Le prénom doit faire plus de 3 caractères !", maxMessage="Le prénom ne doit pas dépassé 15 caractères !")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, max=15, minMessage="Le nom doit faire plus de 3 caractères !", maxMessage="Le nom ne doit pas dépassé 15 caractères !")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veillez renseigner un email valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veillez renseigner un URL valide !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Les deux mots de passes sont différents !")
     */
    private $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=150, minMessage="Le nom doit faire plus de 10 caractères !", maxMessage="Le nom ne doit pas dépassé 150 caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, max=1000, minMessage="Le nom doit faire plus de 100 caractères !", maxMessage="Le nom ne doit pas dépassé 1000 caractères !")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * Permet d'initialiser le slug a chaque évènement prés persist
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initializeSlug(): void
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPasswordConfirm()
    {
        return $this->passwordConfirm;
    }

    /**
     * @param mixed $passwordConfirm
     */
    public function setPasswordConfirm($passwordConfirm): void
    {
        $this->passwordConfirm = $passwordConfirm;
    }


    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->toArray();
        //dump($roles);
        $roles = $this->userRoles->map(function ($role){
            return $role->getTitle();
        })->toArray();
        $roles[] = 'ROLE_USER';
       // dump($roles);
        //die();

        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\DataTranformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends ApplicationType
{
    private $transformer;

    /**
     * BookingType constructor.
     * @param $transformer
     */
    public function __construct(FrenchToDateTimeTransformer $transformer)
    {
        $this->transformer = $transformer;
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {


        $builder
            ->add('startDate', TextType::class, $this->getConfiguration("Date d'arrivée", "La date de votre arrivée"))
            ->add('endDate', TextType::class, $this->getConfiguration("Date de départ", "La date de votre départ"))
            ->add('comment', TextareaType::class, $this->getConfiguration("Commentaire", "Si vous avez un commentaire n'hésitez pas à nous écrire !",
                [
                    'required' => false
                ]));
        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
             "validation_groups"=>["Default", "front"]
        ]);
    }
}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="/CSS/bookingForm.css">
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Medula+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">

{% endblock %}
{% block title %}Réserver l'annonce {% endblock %}

{% block body %}
    {% set ad = booking.ad %}
    {% set author = ad.author %}

    <div class="container">
        <h1 class="h1">Votre réservation n°: {{ booking.id }}</h1>
    </div>
    {% if app.request.query.get('withAlert') %}

        <div class=" container alert alert-success alert-dismissible fade show" role="alert">
            <strong>Bravo !</strong> Votre réservation auprés de <a
                    href="{{ path('user_show', {'slug': author.slug}) }}"><strong>{{ author.fullName }} </strong></a>Pour
            l'annonce
            <a href="{{ path('ads_show', {'slug': ad.slug}) }}"><strong>{{ ad.title }} </strong></a> a été prise en
            compte !
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

    {% endif %}

    <div class="container wrapper bg-white">

        <div class="row">

            <div class="col">
                <div class="alert- alert-light">
                    <h2 class="h2">Votre hébergement</h2>
                    <h4 class="alert alert-heading"><a
                                href="{{ path('ads_show', {'slug': ad.slug}) }}"> {{ ad.title }}</a></h4>
                    <img class="img-thumbnail" src="{{ ad.coverImage }}">
                    <div class="container">
                        {{ ad.content | raw }}
                        <a class="btn btn-primary" href="{{ path('ads_show', {'slug': ad.slug}) }}">Plus d'infos !</a>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="alert- alert-light card ">
                    <h2 class="h2">Détails</h2>
                    <dl class="row h5 text-info card-header ">
                        <dt class="col-md-4 h5 ">Numéro</dt>
                        <dd class="col-md-8 ">{{ booking.id }}</dd>
                        <dt class="col-md-4 h5 ">Date d'arrivée</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4 h5 ">Date de départ</dt>
                        <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4 h5 ">Nombre de nuits</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4 h5 ">Montant total</dt>
                        <dd class="col-md-8">{{ booking.amount }} &euro;</dd>
                        <dt class="col-md-4 h5 ">Commentaire</dt>
                        <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dd>
                    </dl>
                    <hr>
                    <h2 class="h2">Votre hôte </h2>
                    <div class="row  card-header">
                        <div class="col-3 ">
                            <a href="{{ path('user_show', {'slug': author.slug}) }}">
                                <img class="avatar  rounded-circle" src="{{ author.picture }}"
                                     alt="{{ author.fullName }}"></a>
                        </div>
                        <div class="col-9">
                            <a href="{{ path('user_show', {'slug': author.slug}) }}"><h3
                                        class="">{{ author.fullName }}</h3></a>
                            <span class=" badge badge-primary"> {{ author.ads | length }} annonces</span>
                        </div>
                    </div>
                    <div class="container">
                        {{ author.description | raw }}
                        <a class="btn btn-primary" href="{{ path('user_show', {'slug': author.slug}) }}">Plus d'infos
                            sur {{ author.firstName }} !</a>
                    </div>
                </div>
            </div>
            <div class="container" id="comment">
                <h2 class="h2">Votre avis compte !</h2>
                {% if date() > date(booking.endDate) %}

                {% set comment = booking.ad.commentFromAuthor(app.user) %}

                {% if comment is not null %}
                <blockquote>
                    {{ comment.content }}

                </blockquote>
                <strong>Note : </strong>{% include 'shared/rating.html.twig' with {'rating': comment.rating} %}

                {% else %}
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#form">Laisser un
                    commentaire ?
                </button>
                <div class="modal fade" id="form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="text-right cross"><i class="fa fa-times mr-2"></i></div>
                            <div class="card-body text-center"><img class="img-thumbnail" src="{{ ad.coverImage }}"
                                                                    height="100" width="100">
                                <div class="comment-box text-center">
                                    <h4>Add a comment</h4>
                                    {{ form_start(form) }}
                                    <div class="rating">

                                        <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
                                        <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
                                        <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
                                        <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
                                        <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
                                    </div>
                                    {{ form_row(form.rating) }}
                                    {{ form_row(form.content) }}

                                </div>
                                <div class="text-center mt-4">
                                    <button type="submit" class="btn btn-success send px-5">Send message <i
                                                class="fa fa-long-arrow-right ml-1"></i></button>
                                    <button type="button" id="close" class="btn btn-danger ">Annuler</button>
                                </div>
                                {{ form_end(form) }}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% else %}
                <p>Vous ne pourez pas noter cette annonce tant que votre voyage ne sera pas complet !</p>

            {% endif %}

        </div>

    </div>
    </div>


{% endblock %}
{% block javascripts %}
    <script>
        $(document).ready(function () {
            // Open modal on page load
            // $("#form").modal('show');

            // Close modal on button click
            $("#close").click(function () {
                $("#form").modal('hide');
            });
        });
    </script>
{% endblock %}