src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Repository\AdRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Une autre annoce possède dejâ ce titre !"
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères !", maxMessage="Le titre ne doit pas dépassé 255 caractères !")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=25, minMessage="Votre introduction doit faire plus de 20 caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description doit faire au moin de 100 caractères !")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(
     *    message = "L' url: '{{ value }}' n'est pas valide !",
     * )
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug a chaque évènement prés persist
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initializeSlug(): void
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour cette annonce
     *
     * @return float
     */
    public function getAvgRatings() {
        // Calculer la sommes des notations
        $sum = array_reduce($this->comments->toArray(), function($total, $comment) {
            return $total + $comment->getRating();
        }, 0);
        // Faire la division pour avoir la moyenne
        if(count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * @param User $author
     * @return comment|null
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if ($comment->getAuthor() === $author) return $comment;

        }
        return null;
    }

    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette anonce
     * @return array Un tableau d'objets DateTime représentant les jours d'occupation
     */
    /*
    public function getNotAvailableDays(){
        $notAvailableDays = [];

        foreach ($this->getBookings() as  $booking){
            //Calculer les jours qui se trouvent entre la date d'arrivée et de départ
            //$result = range(10, 18, 2)
            //$result = [10, 12, 14, 16, 18]
            $result = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24*60*60
            );

            $days = array_map(
                function ($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            },
                $result );

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }
    */

    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array Un tableau d'objets DateTime représentant les jours d'occupation
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];

        foreach ($this->bookings as $booking) {
            // Calculer les jours qui se trouvent entre la date d'arrivée et de départ
            $resultat = range(
                $booking->getStartDate()->getTimeStamp(),
                $booking->getEndDate()->getTimeStamp(),
                24 * 60 * 60
            );

            $days = array_map(function ($dayTimeStamp) {
                return new \DateTime(date('Y-m-d', $dayTimeStamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdType extends ApplicationType
{



    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration('Titre', 'Tapez un titre pour votre annonce'))
            ->add('slug', TextType::class, $this->getConfiguration('Adresse web', "Tapez l'adresse web(automatique)", [
                'required' => false
            ])
            )
            ->add('coverImage', UrlType::class, $this->getConfiguration('URL de l\'image principale', 'Donnez l\'adresse de votre image'))
            ->add('introduction', TextType::class, $this->getConfiguration('Introduction', 'Donnez une description globale'))
            ->add('content', TextareaType::class, $this->getConfiguration('Description', 'Tapez la description de votre bien'))
            ->add('price', MoneyType::class, $this->getConfiguration('Prix', 'Indiquez le prix pour un nuit'))
            ->add('rooms', IntegerType::class, $this->getConfiguration('Nombre de chambres', 'Tapez le nombre de chambres disponible'))
            ->add(
                'images',
                CollectionType::class, [
                'entry_type' => ImageType::class,
                'allow_add' => true,
                'allow_delete' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Repository\AdRepository;
use App\Service\Paginator;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdController extends AbstractController
{
    /**
     * @Route("/ads/{page<\d+>?1}", name="ads_index")
     */
    public function index(AdRepository $repository, $page, Paginator $paginator): Response
    {
        $paginator->setEntityClass(Ad::class)
            ->setLimit(9)
            ->setPage($page);
        //$session->set('panier', 'mon panier ');
        //dump($session->get('panier'));
        $ads = $repository->findAll();
        return $this->render('ad/index.html.twig', [
            'pagination' => $paginator
        ]);
    }

    /**
     * Permet de créer une nouvelle annonce
     * @Route ("ads/new" , name="ads_create")
     * @IsGranted("ROLE_USER")
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $manager): Response
    {
        $ad = new Ad();

        $form = $this->createForm(AdType::class, $ad);
        //faire le lien avec les information du formulaire et les champ de la class Ad
        $form->handleRequest($request);
        //dump($ad);
        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }
            $ad->setAuthor($this->getUser());
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash('success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée ! "
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'éditer une nouvelle annonce
     * @Route ("ads/{slug}/edit" , name="ads_edit")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier !" )
     * @return Response
     */
    public function edit(Ad $ad, Request $request, EntityManagerInterface $manager): Response
    {
        $form = $this->createForm(AdType::class, $ad);

        //faire le lien avec les information du formulaire et les champ de la class Ad
        $form->handleRequest($request);
        //dump($ad);
        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash('success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été modofiée ! "
            );

            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }


    /**
     * Permet d'afficher une seule annonce
     * @Route("/ads/{slug}", name="ads_show")
     * @return Response
     */
    public function show(Ad $ad): Response
    {
        //$ad = $repository->findOneBySlug($slug); grace au parameter converter on n'a plus besoin du repository c'es symfony qui s'occupe
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    }

    /**
     * Permet de supprimer une seule annonce
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @Security ("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous n'avez pas le droit d'accéder à cette ressource")
     * @param Ad $ad
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function delete(Ad $ad, EntityManagerInterface $manager): Response
    {
        //$ad = $repository->findOneBySlug($slug); grace au parameter converter on n'a plus besoin du repository c'es symfony qui s'occupe
        $manager->remove($ad);
        $manager->flush();
        $this->addFlash('success', "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée !");
        return $this->redirectToRoute('ads_index');
    }

}

templates/ad/_ad.html.twig
{% set url = path('ads_show', { 'slug': ad.slug}) %}
<div class="col-md-4">
    <div class="card  mb-3">
        <div class="card-header text-center">
            <p>
                {% if app.user and app.user == ad.author %}
                    <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-dark"><i class="fas fa-cogs"></i></a>
                {% endif %}
               <em>{{ ad.rooms }}</em>  chambres <i class="fas fa-restroom"></i>, <strong>{{ ad.price | number_format(2, ',', ' ')}}&euro; /nuit</strong></p>
            <p><small>
                    {% if ad.comments|length > 0 %}
                        <div class="container">
                            {% include 'shared/rating.html.twig' with {'rating': ad.avgRatings} %}
                        </div>
                        {% else %}
                      <small>pas encore noté !</small>
                    {% endif %}

                </small></p>
        </div>
        <a href="{{ url }}">
            <img class="img-thumbnail rounded" src="{{ ad.coverImage }}" alt="Image de l'appartement"
                 style="height: 200px; width: 100%; display: block">
        </a>

        <div class="card-body">
            <a href="{{ url }}">
                <h4 class="card-title">
                    {{ ad.title }}
                </h4>
            </a>
            <p class="card-text " >
                {{ ad.introduction }}

            </p>
            <a href="{{ url }}" class="btn btn-info float-right mt-4 btn-sm">En savoir
                plus !</a>

        </div>
    </div>
</div>

templates/ad/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Nos annonces {% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-4 justify-content-center"> Les annonces de nos hôtes</h1>

        <div class="row">
            {% for ad in pagination.data %}
                {% include'/ad/_ad.html.twig' %}
            {% endfor %}
        </div>
        {{ pagination.display() }}
    </div>

{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}
    <div class="my-title m-0 p-0" style="background-image: url({{ ad.coverImage }})">
        <div class=" ad-title text-center">
            <h1 class="h1 text-white ad-title">{{ ad.title }}</h1>
            <p>{{ ad.introduction }}</p>
            <p class="h2 ad-title">
                <strong>{{ ad.rooms }} chambres</strong> pour <strong>{{ ad.price }}&euro;</strong> par nuit
            </p>
            <a href="{{ path('booking_create', {'slug': ad.slug}) }}" class="btn btn-primary btn-lg rounded"><i
                        class="fab fa-cc-visa"></i> Réserver !</a>

            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {'slug' : ad.slug}) }}" class="btn btn-secondary btn-sm"><i
                            class="fas fa-tools"></i> Modifier</a>
                <a type="button" class="btn btn-danger btn-sm text-white" data-toggle="modal"
                   data-target="#exampleModal"><i class="fas fa-trash-alt"></i> Supprimer</a>

            {% endif %}

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <div class="container d-flex pl-0"><i class="fas fa-trash-alt"></i>
                                <h5 class="modal-title ml-2" id="exampleModalLabel"><i
                                            class="fas fa-trash-alt"></i>
                                    Supprimer l'annonce ?</h5>
                            </div>
                            <button type="button" class="close" data-dismiss="modal"
                                    aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="modal-body">
                            <p class="text-muted">Si vous supprimez, l'annonce {{ ad.title }} disparaîtra
                                pour
                                toujours. Êtes-vous
                                sur de vouloir continuer?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-light" data-dismiss="modal">Annuler
                            </button>
                            <a href="{{ path('ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger">

                                <button type="button" class="btn btn-danger"><i
                                            class="fas fa-trash-alt"></i>
                                    Supprimer
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#
    <a href="{{ path('ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger"
       onclick="return confirm(`Ëte vous sur de vouloir supprimer l'annone: {{ ad.title }} ?`)">
       <i class="fas fa-trash-alt"></i>
        Supprimer cette annonce </a>
    #}

    <div class="container">
        <div class="row ">
            <div class="col-md-8 mb-3">
               <div class="container bg-white rounded p-4">{{ ad.content | raw }}</div>

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}"
                                {% if loop.first %}class="active" {% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                            <div class="carousel-item {% if loop.first %}active {% endif %}">
                                <img src="{{ image.url }}" class="d-block w-100 img-thumbnail" alt="Images Annonces">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ ad.title }}</h5>
                                    <p>{{ image.caption }}</p>
                                </div>

                            </div>
                        {% endfor %}

                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <hr>
                {% if ad.comments|length > 0 %}
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col text-center mb-5">
                            <div class="card rating_square">
                                <div class="row justify-content-left d-flex">

                                    <div class="col-md-4 d-flex flex-column">
                                        <div class="rating-box">
                                            <h2 class="pt-4 h4">{{ ad.avgRatings| number_format(2) }}/5</h2>
                                            <small>(Nombre d'avis: {{ ad.comments| length }})</small>
                                        </div>

                                        <div class="container">
                                            {% include 'shared/rating.html.twig' with {'rating': ad.avgRatings} %}

                                        </div>

                                    </div>

                                    <div class="col">
                                        <div class="rating-bar0 justify-content-center">
                                            <table class="text-left mx-auto">
                                                <tr>
                                                    <td class="rating-label">Excellent</td>
                                                    <td class="rating-bar">
                                                        <div class="bar-container">
                                                            <div class="bar-5"></div>
                                                        </div>
                                                    </td>
                                                    <td class="text-right">123</td>
                                                </tr>
                                                <tr>
                                                    <td class="rating-label">Good</td>
                                                    <td class="rating-bar">
                                                        <div class="bar-container">
                                                            <div class="bar-4"></div>
                                                        </div>
                                                    </td>
                                                    <td class="text-right">23</td>
                                                </tr>
                                                <tr>
                                                    <td class="rating-label">Average</td>
                                                    <td class="rating-bar">
                                                        <div class="bar-container">
                                                            <div class="bar-3"></div>
                                                        </div>
                                                    </td>
                                                    <td class="text-right">10</td>
                                                </tr>
                                                <tr>
                                                    <td class="rating-label">Poor</td>
                                                    <td class="rating-bar">
                                                        <div class="bar-container">
                                                            <div class="bar-2"></div>
                                                        </div>
                                                    </td>
                                                    <td class="text-right">3</td>
                                                </tr>
                                                <tr>
                                                    <td class="rating-label">Terrible</td>
                                                    <td class="rating-bar">
                                                        <div class="bar-container">
                                                            <div class="bar-1"></div>
                                                        </div>
                                                    </td>
                                                    <td class="text-right">0</td>
                                                </tr>
                                            </table>
                                        </div>

                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                {% endif %}

                {% if ad.comments|length > 0 %}
                    {% for comment in ad.comments %}
                        <div class=" bg-light rounded mb-3 py-3 px-3">
                            <a href="{{ path('user_show', {'slug': comment.author.slug}) }}">
                                <img class="avatar-medium rounded-circle" src="{{ comment.author.picture }}"
                                     alt="{{ comment.author.fullName }}"
                                     width="36px"/> <strong>{{ comment.author.fullName }}: </strong>
                            </a>
                            {% include 'shared/rating.html.twig' with {'rating': comment.rating} %}
                            <blockquote>{{ comment.content }}</blockquote>
                        </div>

                    {% endfor %}

                {% else %}
                    <blockquote class="alert alert-info">
                      Cette annonce n'a pas encore reçu de commentaire !
                    </blockquote>
                {% endif %}
            </div>

            <div class="container mb-3 d-flex justify-content-center col-md-4 align-items-start">
                <div class="card rounded">
                    {% set a = ad.author %}
                    <div class=" d-block justify-content-center">
                        <div class="area1 p-3 py-5 text-center"><h5 class=" h5 mb-4"> {{ a.ads| length }} annonces</h5>
                        </div>
                        <div class="area2 p- text-center px-3">
                            <div class="image mr-3  ">
                                <a href="{{ path('user_show', {'slug': a.slug}) }}">
                                    <img src="{{ a.picture }}" class="rounded-circle" width="100"
                                         alt="avatar de {{ a.fullName }}"/>
                                </a>
                                <a href="{{ path('user_show', {'slug': a.slug}) }}">
                                    <h4 class=" name mt-3 ">{{ a.fullName }}</h4></a>
                                <p class="information mt-3 text-justify"> {{ a.description |raw }} </p>
                                <div class="d-flex justify-content-center mt-4">
                                    <ul class="list-icons">
                                        <li class="facebook"><i class="fab fa-facebook-square"></i></li>
                                        <li class="youtube"><i class="fab fa-youtube-square"></i></li>
                                        <li class="instagram"><i class="fab fa-instagram"></i></li>
                                        <li class="whatsapp"><i class="fab fa-whatsapp-square"></i></li>
                                    </ul>
                                </div>
                            </div>
                            <div></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}